### ISSUE TITLE
[Request] support preview content in Fantia product page

### ISSUE THREAD

**Issue by ian040504** [KJHJason/Cultured-Downloader#165]
Request to support preview content, like thumbnails or demo videos, in Fantia product page.

Ref: [https://github.com/KJHJason/Cultured-Downloader/discussions/161](https://github.com/KJHJason/Cultured-Downloader/discussions/161)

**Comment by KJHJason** [comment]
Hey @ian040504, I have added this requested feature into [V5.1.0](https://github.com/KJHJason/Cultured-Downloader/releases/tag/5.1.0), it will also download the paid content if you have previously paid for the product.
