### ISSUE TITLE
[Bug]: Can't download pixiv fanbox 

### ISSUE THREAD

**Issue by Toryu122** [KJHJason/Cultured-Downloader#17]
### Which program are you seeing this problem on?

Cultured Downloader (py)

### Program Version

4.2.1

### Steps to reproduce the bug

1.  
![Capture](https://user-images.githubusercontent.com/92678834/208220297-44248e21-c859-4b12-9056-0fa7086cfdd6.PNG)

### Expected behaviour

I don't know why the link is invalid

### Screenshots (Optional)

![Capture](https://user-images.githubusercontent.com/92678834/208220317-b386383e-aecf-428e-9018-b561c389905d.PNG)

**Comment by KJHJason** [comment]
You are currently in the Pixiv download options, please enter command 3 in the main menu for Pixiv Fanbox download options.

That being said, I have plans to refactor the codes to follow the [CLI version of this program](https://github.com/KJHJason/Cultured-Downloader-CLI) which has better download capabilities like better quality conversion for Pixiv's ugoira.
