### ISSUE TITLE
[Bug]: (Kemono download speed extremely slow）

### ISSUE THREAD

**Issue by onmymomma001** [KJHJason/Cultured-Downloader#244]
### Which program are you seeing this problem on?

Cultured Downloader (Go)

### Program Version

Version 5.1.0

### Operating System

Windows 10

### What error code did you receive? (If any)

1007 (Download Error)

### Steps to reproduce the bug

1. When downloading from kemono posts scraping behavior and downloading is extremely slow
2. 
3. 
4.

### Expected behaviour

I had installed the program just fine not sure why I am getting download speeds that are 0.06MB/s and I was wondering if it was on my part as I had closed all other programs hogging network speed or is it some kind of DDOS protection on kemono's part. I had tried downloading from favorites as well as other creators any help would be appreciated!

### Screenshots (Optional)

![download speed](https://github.com/KJHJason/Cultured-Downloader/assets/84560646/eac256ea-cc80-495f-adc8-dcf04d5c1dfe)

**Comment by KJHJason** [comment]
This is not a bug. Kemono's servers are the ones throttling the bandwidth. Hence, I can't do much about the download speed.

Even on my end, Kemono averages around 0.1-0.6MB/s which is really slow.

On the other hand, that's the main reason why I added the caching feature. It helps to avoid sending unnecessary requests to an already downloaded post to speed up the download process.

Thus, the more frequently you download from the SAME artist, the more posts the program caches and the faster your future download process gets.

**Comment by KJHJason** [comment]
However, I could probably increase the speed slightly by removing the unnecessary HEAD request to Kemono.
