### ISSUE TITLE
[Bug]: Pixiv Fanbox 1006 response error

### ISSUE THREAD

**Issue by HoopesC** [KJHJason/Cultured-Downloader#288]
### Which program are you seeing this problem on?

Cultured Downloader (Go)

### Program Version

Version 5.1.0

### Operating System

Windows 11

### What error code did you receive? (If any)

1006 (Response Error)

### Steps to reproduce the bug

1. Start download with any user (User on this run: https://www.fanbox.cc/@koutarong)
2. Wait for program to get post IDs
3. Failure
4. (Note: Pixiv Fanbox downloader only works for me if I am using a VPN in Japan.)

### Expected behaviour

It is expected that the program will properly gather post IDs and start downloading. 

### Relevant log output (If any)

<html>
<body>

Body: {"body":[{"id":"7369169","title":"\u30ca\u30fc\u30b9\u3055\u3093","feeRequired":550,"publishedDatetime":"2024-01-29T00:39:15+09:00","updatedDatetime":"2024-06-01T12:12:11+09:00","tags":["\u30d0\u30c3\u30af\u30ca\u30f3\u30d0\u30fc02"],"isLiked":false,"likeCount":69,"commentCount":2,"isRestricted":false,"user":{"userId":"160924","name":"\u3053\u3046\u305f\u308d","iconUrl":"https:\/\/pixiv.pximg.net\/c\/160x160_90_a2_g5\/fanbox\/public\/images\/user\/160924\/icon\/cQwgXTQFJefmtLrTD2cLVLdy.jpeg"},"creatorId":"koutarong","hasAdultContent":true,"cover":{"type":"cover_image","url":"https:\/\/pixiv.pximg.net\/c\/1200x630_90_a2_g5\/fanbox\/public\/images\/post\/7369169\/cover\/n6DIzHTyEj49xkxdIsu8l9GT.jpeg"},"excerpt":"\u6614\u63cf\u3044\u305f\u30ca\u30fc\u30b9\u3055\u3093\u306e\u52a0\u7b46\u5dee\u5206\u3067\u3059\uff5e\n\u30d0\u30c3\u30af\u30ca\u30f3\u30d0\u30fc\u3092\u304a\u6c42\u3081\u306e\u65b9\u306f\u3053\u3061\u3089\nhttps:\/\/koutarong.fanbox.cc\/posts\/7571467"},{"id":"7342178","title":"\u5984\u60f3\u30b7\u30ea\u30fc\u30ba\u3000\u4f53\u64cd\u670d\u30de\u30d5\u30e9\u30fc","feeRequired":550,"publishedDatetime":"2024-01-23T13:19:56+09:00","updatedDatetime":"2024-06-01T12:12:20+09:00","tags":["\u30d0\u30c3\u30af\u30ca\u30f3\u30d0\u30fc02"],"isLiked":false,"likeCount":94,"commentCount":1,"isRestricted":false,"user":{"userId":"160924","name":"\u3053\u3046\u305f\u308d","iconUrl":"https:\/\/pixiv.pximg.net\/c\/160x160_90_a2_g5\/fanbox\/public\/images\/user\/160924\/icon\/cQwgXTQFJefmtLrTD2cLVLdy.jpeg"},"creatorId":"koutarong","hasAdultContent":true,"cover":{"type":"cover_image","url":"https:\/\/pixiv.pximg.net\/c\/1200x630_90_a2_g5\/fanbox\/public\/images\/post\/7342178\/cover\/xnz1drRHcCufFKwEB1Jon8hZ.jpeg"},"excerpt":"\u30b9\u30b1\u30b9\u30b1\u3071\u3093\u3064\u306b\u3057\u3066\u307f\u307e\u3057\u305f\n4\u679a\u76ee\u306f\u3076\u3063\u304b\u3051\u3067\u3059\n\u30d0\u30c3\u30af\u30ca\u30f3\u30d0\u30fc\u3092\u304a\u6c42\u3081\u306e\u65b9\u306f\u3053\u3061\u3089\nhttps:\/\/koutarong.fanbox.cc\/posts\/7571467"},{"id":"7274059","title":"K\u5ba4\u3057\u3083\u304c\u30d1\u30f3","feeRequired":550,"publishedDatetime":"2024-01-09T01:12:00+09:00","updatedDatetime":"2024-06-01T12:12:31+09:00","tags":["\u30d0\u30c3\u30af\u30ca\u30f3\u30d0\u30fc02"],"isLiked":false,"likeCount":86,"commentCount":8,"isRestricted":false,"user":{"userId":"160924","name":"\u3053\u3046\u305f\u308d","iconUrl":"https:\/\/pixiv.pximg.net\/c\/160x160_90_a2_g5\/fanbox\/public\/images\/user\/160924\/icon\/cQwgXTQFJefmtLrTD2cLVLdy.jpeg"},"creatorId":"koutarong","hasAdultContent":true,"cover":{"type":"cover_image","url":"https:\/\/pixiv.pximg.net\/c\/1200x630_90_a2_g5\/fanbox\/public\/images\/post\/7274059\/cover\/eI2R7LpM6cIjmky25TvD08YH.jpeg"},"excerpt":"\u3042\u3051\u304a\u3081\u3067\u3059\uff5e\u4eca\u5e74\u3082\u3088\u308d\u3057\u304f\u304a\u9858\u3044\u3057\u307e\u3059\n\u4ee5\u524d\u306e\u3057\u3083\u304c\u307f\u7d75\u3092\u52a0\u7b46\u3057\u307e\u3057\u305f\ud83d\ude0a\n\u30d0\u30c3\u30af\u30ca\u30f3\u30d0\u30fc\u3092\u304a\u6c42\u3081\u306e\u65b9\u306f\u3053\u3061\u3089\nhttps:\/\/koutarong.fanbox.cc\/posts\/7571467"},{"id":"7215777","title":"\u5984\u60f3\u30b7\u30ea\u30fc\u30ba\u3000\u98df\u3044\u8fbc\u307f","feeRequired":550,"publishedDatetime":"2023-12-30T08:46:59+09:00","updatedDatetime":"2024-06-01T12:12:41+09:00","tags":["\u30d0\u30c3\u30af\u30ca\u30f3\u30d0\u30fc02"],"isLiked":false,"likeCount":102,"commentCount":6,"isRestricted":false,"user":{"userId":"160924","name":"\u3053\u3046\u305f\u308d","iconUrl":"https:\/\/pixiv.pximg.net\/c\/160x160_90_a2_g5\/fanbox\/public\/images\/user\/160924\/icon\/cQwgXTQFJefmtLrTD2cLVLdy.jpeg"},"creatorId":"koutarong","hasAdultContent":true,"cover":{"type":"cover_image","url":"https:\/\/pixiv.pximg.net\/c\/1200x630_90_a2_g5\/fanbox\/public\/images\/post\/7215777\/cover\/xrmi3FweVtgiJNcr61cjfEPm.jpeg"},"excerpt":"\u524d\u304b\u3089\u63cf\u3044\u3066\u307f\u305f\u304b\u3063\u305f\u7dbf\u30d1\u30f3\u30c4+\u7d10\u98df\u3044\u8fbc\u307f\u3067\u3059\u3002\n\u672c\u5e74\u5ea6\u63cf\u304d\u53ce\u3081\u3067\u3059\u304c\u6765\u5e74\u3082\u3088\u308d\u3057\u304f\u304a\u9858\u3044\u3057\u307e\u3059\uff01\n\u30d0\u30c3\u30af\u30ca\u30f3\u30d0\u30fc\u3092\u304a\u6c42\u3081\u306e\u65b9\u306f\u3053\u3061\u3089\nhttps:\/\/koutarong.fanbox.cc\/posts\/7571467"},{"id":"7159477","title":"\u30c8\u30e9\u8033\u3055\u3093","feeRequired":550,"publishedDatetime":"2023-12-19T18:16:19+09:00","updatedDatetime":"2024-06-01T12:12:53+09:00","tags":["\u30d0\u30c3\u30af\u30ca\u30f3\u30d0\u30fc01"],"isLiked":false,"likeCount":88,"commentCount":8,"isRestricted":false,"user":{"userId":"160924","name":"\u3053\u3046\u305f\u308d","iconUrl":"https:\/\/pixiv.pximg.net\/c\/160x160_90_a2_g5\/fanbox\/public\/images\/user\/160924\/icon\/cQwgXTQFJefmtLrTD2cLVLdy.jpeg"},"creatorId":"koutarong","hasAdultContent":true,"cover":{"type":"cover_image","url":"https:\/\/pixiv.pximg.net\/c\/1200x630_90_a2_g5\/fanbox\/public\/images\/post\/7159477\/cover\/XOW8KGoPS3BEzIn4cr56frli.jpeg"},"excerpt":"\u4ee5\u524d\u63cf\u3044\u305f\u864e\u3055\u3093\u306e\u5dee\u5206\u3067\u3059\n\u30d0\u30c3\u30af\u30ca\u30f3\u30d0\u30fc\u3092\u304a\u6c42\u3081\u306e\u65b9\u306f\u3053\u3061\u3089\nhttps:\/\/koutarong.fanbox.cc\/posts\/7571465"},{"id":"7138501","title":"\u5984\u60f3\u30b7\u30ea\u30fc\u30ba\u3000\u9732\u51fa","feeRequired":550,"publishedDatetime":"2023-12-15T09:53:14+09:00","updatedDatetime":"2024-06-01T12:13:03+09:00","tags":["\u30d0\u30c3\u30af\u30ca\u30f3\u30d0\u30fc01"],"isLiked":false,"likeCount":98,"commentCount":8,"isRestricted":false,"user":{"userId":"160924","name":"\u3053\u3046\u305f\u308d","iconUrl":"https:\/\/pixiv.pximg.net\/c\/160x160_90_a2_g5\/fanbox\/public\/images\/user\/160924\/icon\/cQwgXTQFJefmtLrTD2cLVLdy.jpeg"},"creatorId":"koutarong","hasAdultContent":true,"cover":{"type":"cover_image","url":"https:\/\/pixiv.pximg.net\/c\/1200x630_90_a2_g5\/fanbox\/public\/images\/post\/7138501\/cover\/lIjEdM13GQUbJAJdcigr8TfB.jpeg"},"excerpt":"\u3053\u3093\u306a\u3068\u3053\u308d\u3067\u3068\u3093\u3067\u3082J\u3055\u3093\u3067\u3059\n\u30d0\u30c3\u30af\u30ca\u30f3\u30d0\u30fc\u3092\u304a\u6c42\u3081\u306e\u65b9\u306f\u3053\u3061\u3089\nhttps:\/\/koutarong.fanbox.cc\/posts\/7571465\n"},{"id":"7087333","title":"12\u6708\uff5e","feeRequired":550,"publishedDatetime":"2023-12-04T07:52:37+09:00","updatedDatetime":"2024-06-01T12:13:17+09:00","tags":["\u30d0\u30c3\u30af\u30ca\u30f3\u30d0\u30fc01"],"isLiked":false,"likeCount":89,"commentCount":5,"isRestricted":false,"user":{"userId":"160924","name":"\u3053\u3046\u305f\u308d","iconUrl":"https:\/\/pixiv.pximg.net\/c\/160x160_90_a2_g5\/fanbox\/public\/images\/user\/160924\/icon\/cQwgXTQFJefmtLrTD2cLVLdy.jpeg"},"creatorId":"koutarong","hasAdultContent":true,"cover":{"type":"cover_image","url":"https:\/\/pixiv.pximg.net\/c\/1200x630_90_a2_g5\/fanbox\/public\/images\/post\/7087333\/cover\/LmHQC06zSSd86qjeFaiAs7MB.jpeg"},"excerpt":"\u524d\u306b\u63cf\u3044\u305f\u30b5\u30f3\u30bf\u3055\u3093\u306e\u5dee\u5206\u7d75\u3067\u3059\ud83d\ude0a\n\u30d0\u30c3\u30af\u30ca\u30f3\u30d0\u30fc\u3092\u304a\u6c42\u3081\u306e\u65b9\u306f\u3053\u3061\u3089\nhttps:\/\/koutarong.fanbox.cc\/posts\/7571465"},{"id":"7034127","title":"\u90e8\u5c4b\u3067\u305d\u306e\u5f8c","feeRequired":550,"publishedDatetime":"2023-11-25T00:46:23+09:00","updatedDatetime":"2024-06-01T12:13:25+09:00","tags":["\u30d0\u30c3\u30af\u30ca\u30f3\u30d0\u30fc01"],"isLiked":false,"likeCount":94,"commentCount":10,"isRestricted":false,"user":{"userId":"160924","name":"\u3053\u3046\u305f\u308d","iconUrl":"https:\/\/pixiv.pximg.net\/c\/160x160_90_a2_g5\/fanbox\/public\/images\/user\/160924\/icon\/cQwgXTQFJefmtLrTD2cLVLdy.jpeg"},"creatorId":"koutarong","hasAdultContent":true,"cover":{"type":"cover_image","url":"https:\/\/pixiv.pximg.net\/c\/1200x630_90_a2_g5\/fanbox\/public\/images\/post\/7034127\/cover\/Te3Iuc5UJqtVCF0VKgscQruH.jpeg"},"excerpt":"\u4ee5\u524d\u63cf\u3044\u305f\u7d75\u306e\u5dee\u5206\u3067\u3059\u266a\n\u30d0\u30c3\u30af\u30ca\u30f3\u30d0\u30fc\u3092\u304a\u6c42\u3081\u306e\u65b9\u306f\u3053\u3061\u3089\nhttps:\/\/koutarong.fanbox.cc\/posts\/7571465"},{"id":"7004508","title":"H\u5dee\u5206","feeRequired":550,"publishedDatetime":"2023-11-18T18:09:01+09:00","updatedDatetime":"2024-06-01T12:13:34+09:00","tags":["\u30d0\u30c3\u30af\u30ca\u30f3\u30d0\u30fc01"],"isLiked":false,"likeCount":99,"commentCount":11,"isRestricted":false,"user":{"userId":"160924","name":"\u3053\u3046\u305f\u308d","iconUrl":"https:\/\/pixiv.pximg.net\/c\/160x160_90_a2_g5\/fanbox\/public\/images\/user\/160924\/icon\/cQwgXTQFJefmtLrTD2cLVLdy.jpeg"},"creatorId":"koutarong","hasAdultContent":true,"cover":{"type":"cover_image","url":"https:\/\/pixiv.pximg.net\/c\/1200x630_90_a2_g5\/fanbox\/public\/images\/post\/7004508\/cover\/v1E0OmtbAEz5OTfxshaoF8Do.jpeg"},"excerpt":"\u521d\u6295\u7a3f\u3067\u3059\u3002\u3088\u308d\u3057\u304f\u304a\u9858\u3044\u3057\u307e\u3059\uff5e\u266a\n\u30d0\u30c3\u30af\u30ca\u30f3\u30d0\u30fc\u3092\u304a\u6c42\u3081\u306e\u65b9\u306f\u3053\u3061\u3089\nhttps:\/\/koutarong.fanbox.cc\/posts\/7571465"}]} |  
-- | --

<br class="Apple-interchange-newline">
</body>
</html>

**Comment by KJHJason** [comment]
Please update the issue title in the future.

From your provided "logs", I am unable to identify the exact cause but guess that it might be related to #259

**Comment by HoopesC** [comment]
Apologies about the title. I have edited that.

Here is a link to full log output in case it helps: https://nopaste.net/CIAFdgHJpt

**Comment by KJHJason** [comment]
Thanks, from the logs, I can now identify the exact issue.
it doesn't seem to be related to #259 but it looks like Pixiv Fanbox has changed the JSON structure which should be a simple fix.
